function history(){
    document.getElementById("demo").innerHTML="<p>There were conflicting stories on how Atimonan got its name. Some concluded that the name Atimonan originated from a tree known as Atimon alleged to have been prevalent in the area and had reportedly served many uses to the residents. These trees are now extinct and its non-existence could not be accounted for.</p><p>But the most popular version is that it originated from the name of its founder, Simeona Mangaba, known to her town mates as Ate Monang. She is a woman reputed to be of unquestionable leadership, which the people regarded as their adopted parent, leader and protector.</p>";
}
function culture(){
    document.getElementById("demo2").innerHTML=" <p>People from Atimonan are called Atimonanins. The primary language is Tagalog, with many local phrases and expressions. Manilans usually understand Atimonan Tagalog, albeit with some frustrations. Many Atimonanins are part Chinese or Spanish. Some Atimonanins can also speak Bicolano, Lan-nang, or Spanish.</p><p>The dominant religion in Atimonan is Roman Catholic, though there is a significant following of the Born Again. The culture in Atimonan is primarily ingrained in rural maritime Filipino settings. Weather remains a powerful force in this town.</p>";
}
function tradition(){
     document.getElementById("demo3").innerHTML="<p>The Tagultol Festival is an evolution of various cultural activities, practiced in previous years by Atimonanins. The Town & Patronal Fiesta every August 1 & 2 is simply celebrated with the usual parade, a cultural program, thanksgiving mass and procession. In 1981, during the administration of then Quezon Board Member and then Mayor of Atimonan Remedios V. Diestro, an activity was started – the Karakol. It is a fluvial parade done in the afternoon of the 2nd day of the fiesta. The boats traveled around Lamon Bay within the boundaries of the town proper headed by the Grand Boat where the patron – Nuestra Senora de Los Angeles was aboard. There were singing, dancing & band playing, all in expression of gratitude to the Almighty for the year’s bountiful catch. The parade then joined the religious procession and ended at the church.</p>";
}

